export const event = {
  brideName: "بهاره حبیبی",
  brideNameEn: "BAHARA HABIBI",
  groomName: "امین‌الله عبیدی",
  groomNameEn: "AMINULLAH OBAIDI",
  coupleDisplayName: "امین‌الله عبیدی و بهاره حبیبی",
  pageTitle: "جشن پیوند امین‌الله عبیدی و بهاره حبیبی",
  invitationDateFa: "جمعه، ۲۴ میزان ۱۴۰۵",
  invitationDateGregorian: "16 October 2026",
  startTimeFa: "۶:۰۰ شام",
  endTimeFa: "۱۰:۳۰ شب",
  startDateTimeISO: "2026-10-16T18:00:00+04:30",
  endDateTimeISO: "2026-10-16T22:30:00+04:30",
  venueName: "تالار عروسی تاج کانتیننتال",
  venueNameEn: "Taj Continental Wedding Hall",
  venueShortName: "تالار عروسی تاج کانتیننتال، کابل",
  venueAddressFa: "چهارراهی بارکی، کابل، افغانستان",
  cityFa: "کابل",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=Taj+Continental+Wedding+Hall+Baraki+Square+Kabul+Afghanistan",
  latitude: 34.5325,
  longitude: 69.1415,
  rsvpDeadlineFa: "لطفاً تا ۱۵ میزان پاسخ دهید",
  contactPhoneDisplay: "۰۷۸ ۲۸۷ ۸۷۸۷",
  contactPhoneHref: "tel:+93782878787",
  familyLine: "خانواده‌های عبیدی و حبیبی",
  hashtag: "#AminullahAndBahara",
  dressCodeFa: "لباس رسمی / پیراهن تنبان فاخر یا دریشی / لباس‌های مجلسی با رنگ‌های ملایم، طلایی یا عنابی",
  photos: [] as Array<{ src: string; alt: string }>
} as const;
