export const event = {
  brideName: "ادیبه",
  brideNameEn: "ADEEBA",
  groomName: "فرهاد",
  groomNameEn: "FARHAD",
  coupleDisplayName: "فرهاد و ادیبه",
  pageTitle: "جشن پیوند فرهاد و ادیبه",
  invitationDateFa: "جمعه، ۲۴ میزان ۱۴۰۵",
  invitationDateGregorian: "16 October 2026",
  startTimeFa: "۶:۰۰ شام",
  endTimeFa: "۱۰:۳۰ شب",
  startDateTimeISO: "2026-10-16T18:00:00+04:30",
  endDateTimeISO: "2026-10-16T22:30:00+04:30",
  venueName: "تالار عروسی تاج کانتیننتال",
  venueNameEn: "Taj Continental Wedding Hall",
  venueShortName: "Taj Continental",
  venueAddressFa: "Baraki Square, Kabul 1001, Afghanistan",
  cityFa: "کابل",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=Taj+Continental+Wedding+Hall+Kabul+Afghanistan",
  latitude: 34.53751,
  longitude: 69.14289,
  rsvpDeadlineFa: "لطفاً تا ۱۰ میزان پاسخ دهید",
  contactPhoneDisplay: "+93 78 287 8787",
  contactPhoneHref: "tel:+93782878787",
  website: "tajcontinental.com",
  websiteUrl: "https://tajcontinental.com",
  familyLine: "خانواده‌های رضایی و همت",
  hashtag: "#FarhadAndAdeeba",
  dressCodeFa: "لباس رسمی / پیراهن تنبان فاخر یا دریشی / لباس‌های مجلسی با رنگ‌های ملایم، طلایی یا عنابی",
  photos: [] as Array<{ src: string; alt: string }>
} as const;
