export const event = {
  brideName: "ادیبه",
  brideNameEn: "ADEEBA",
  groomName: "فرهاد",
  groomNameEn: "FARHAD",
  coupleDisplayName: "فرهاد و ادیبه",
  pageTitle: "جشن پیوند فرهاد و ادیبه",
  invitationDateFa: "دوشنبه، ۱۳ میزان ۱۴۰۵",
  invitationDateGregorian: "13 October 2026",
  startTimeFa: "۶:۰۰ شام",
  endTimeFa: "۱۰:۳۰ شب",
  startDateTimeISO: "2026-10-13T18:00:00+04:30",
  endDateTimeISO: "2026-10-13T22:30:00+04:30",
  venueName: "قصر ستاره شهر",
  venueNameEn: "City Star Hotel Kabul",
  venueShortName: "قصر ستاره شهر، کابل",
  venueAddressFa: "کابل، قصر ستاره شهر",
  cityFa: "کابل",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=City+Star+Hotel+Kabul+Afghanistan",
  latitude: 34.528,
  longitude: 69.172,
  rsvpDeadlineFa: "لطفاً تا ۵ میزان پاسخ دهید",
  contactPhoneDisplay: "۰۷۹۹ ۱۲۳ ۴۵۶",
  contactPhoneHref: "tel:+93799123456",
  familyLine: "خانواده‌های رضایی و همت",
  hashtag: "#FarhadAndAdeeba",
  dressCodeFa: "لباس رسمی / پیراهن تنبان فاخر یا دریشی / لباس‌های مجلسی با رنگ‌های ملایم، طلایی یا عنابی",
  photos: [] as Array<{ src: string; alt: string }>
} as const;
